"""Change a column

Revision ID: 43806dcfacb5
Revises: 
Create Date: 2024-01-18 19:22:09.968188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43806dcfacb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SGEComelec', sa.Column('ComelecPassword', sa.Text(), nullable=True))
    op.drop_column('SGEComelec', 'Password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SGEComelec', sa.Column('Password', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('SGEComelec', 'ComelecPassword')
    # ### end Alembic commands ###
